### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Quaziz-creator** [kristoferlund/ic-use-internet-identity#1]
1. Cloned repo
2. install and what not.
3. dfx deploy
4. App starts locally
5. clicking Login
6. http://localhost:4943/?canisterId=undefined#authorize

Fix: Correct this in vite.config.js, to the actual env variable:
const internetIdentityUrl =
  process.env.DFX_NETWORK === "local"
    ? `http://localhost:4943/?canisterId=${process.env.CANISTER_ID_INTERNET_IDENTITY}`
    : `https://identity.ic0.app`;

**Comment by kristoferlund** [comment]
Good catch, thanks. The name of the variable changed with some dfx version. Added change to latest version.
